# Generated by Django 2.0.7 on 2018-09-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('url', models.URLField(help_text='The location of the booking site.')),
                ('open_date', models.DateTimeField(help_text='The date/time which the event will become visible.')),
                ('asset_background', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('asset_art', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('end_action', models.CharField(choices=[('A', 'Archive'), ('H', 'Hide')], default='A', help_text="The action to take after the final event date has passed. Archived events will display under 'Past Events'. Hidden events will not be shown.", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Event')),
            ],
        ),
    ]
