# Generated by Django 2.1.5 on 2019-03-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('booking_url', models.URLField(blank=True, help_text='ex. TryBooking URL', null=True)),
                ('open_date', models.DateTimeField(help_text='The date/time which the event will become visible.')),
                ('thumbnail_img', models.ImageField(blank=True, help_text='The image that will display in the list of events.', null=True, upload_to='images/%Y/%m/%d/')),
                ('hero_img', models.ImageField(blank=True, help_text='The header image that will display on the event page.', null=True, upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('end_action', models.CharField(choices=[('R', 'Archive'), ('H', 'Hide')], default='R', help_text="The action to take after the final event date has passed. Archived events will display under 'Past Events'. Hidden events will not be shown.", max_length=1)),
            ],
            options={
                'ordering': ('open_date',),
            },
        ),
        migrations.CreateModel(
            name='EventDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Event')),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, help_text='Enter the `src` component of an embedded map.', max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Location'),
        ),
    ]
