# Generated by Django 2.1.5 on 2019-01-21 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


def forwards_func(apps, schema_editor):
    SitePreferences = apps.get_model('web', 'SitePreferences')
    db_alias = schema_editor.connection.alias
    if SitePreferences.objects.count() == 0:
        SitePreferences.objects.create(pk=1)


def reverse_func(apps, schema_editor):
    SitePreferences = apps.get_model('web', 'SitePreferences')
    db_alias = schema_editor.connection.alias
    SitePreferences.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('home_title', models.TextField(blank=True, null=True)),
                ('about_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('membership_title', models.CharField(blank=True, max_length=50, null=True)),
                ('membership_text', models.TextField(blank=True, null=True)),
                ('friend_title', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_text', models.TextField(blank=True, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
                ('member_form', models.URLField(blank=True, help_text='The link for the member signup form.', null=True)),
                ('friend_form', models.URLField(blank=True, help_text='The link for the friend signup form.', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook username', max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username', max_length=50, null=True)),
                ('abn', models.CharField(blank=True, help_text='Australian Business Number. Include space formatting as desried.', max_length=20, null=True, verbose_name='ABN')),
            ],
            options={
                'verbose_name': 'Preferences',
                'verbose_name_plural': 'Preferences',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
